---
- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Ansible copy directory with docker-compose to the remote server
    copy:
      src: ../../dockerBasedTools/selenoid-web/
      dest: /home/

  - name: Pull Chrome image
    shell: docker pull selenoid/vnc:chrome_76.0

  - name: Docker compose up
    shell: cd ../ && docker-compose up -d